# Generated by Django 3.2 on 2022-09-15 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buscar_BackEnd_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Término de búsqueda')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Buscar_FrontEnd_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Término de búsqueda')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Imagen_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagina_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('title', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última modificación')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img_proyecto/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img_servicio/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('phone', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('minibio', models.TextField(blank=True, null=True, verbose_name='Mini Biografía')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img_persona/', verbose_name='Imagen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Articulo_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('title', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img_articulo/', verbose_name='Imagen')),
                ('draft', models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última modificación')),
                ('fk_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.categoria_model', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['id'],
            },
        ),
    ]
