# Generated by Django 3.2 on 2022-09-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_mensaje_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje_model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
