# Generated by Django 3.2 on 2022-09-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_mensaje_model_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_model',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona_model',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proyecto_model',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='servicio_model',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
