# Generated by Django 3.2 on 2022-09-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20220915_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_model',
            name='fk_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.categoria_model', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='servicio_model',
            name='fk_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.categoria_model', verbose_name='Categoría'),
        ),
    ]
